version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: savvy-postgres
    environment:
      POSTGRES_DB: savvy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build: .
    container_name: savvy-api
    environment:
      ENV: development
      PORT: 8080
      HOST: 0.0.0.0
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: savvy
      DB_SSL_MODE: disable
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      JWT_EXPIRY: 24h
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app
    command: go run cmd/server/main.go
    restart: unless-stopped

volumes:
  postgres_data:
